apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: flaskv1.azurecr.io/myapp:${{ github.sha }}  # Replace with your image location
        ports:
        - containerPort: 5000
