apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
  namespace: workflowv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: acrworkflow1697645774741.azurecr.io/image-workflow-1697645774741:latest
          ports:
            - containerPort: 8000