name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-to-aci:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        run: |
          az login  --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: acigroupv2
          dns-name-label: flaskwebv2
          image: flaskv2.azurecr.io/flaskhello:latest
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aciflaskv2
          restart-policy: Never
          location: 'Canada Central'
