name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v4

      # Add a new step to install pytest and then run pytest
      - name: Install dependencies and run pytest
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest
