name: Build and Push Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/flaskv2:${{ github.sha }}
          file: Dockerfile

      -
        name: Checkout for ACR Push
        uses: actions/checkout@v2

      -
        name: Docker Login for ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      -
        name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: flaskv2.azurecr.io/aspcoresample:${{ github.sha }}
          file: Dockerfile
